### ISSUE TITLE
This method has an aromatize step, and that needs to be removed now

### ISSUE THREAD

**Issue by tylerperyea** [ncats/structure-indexer#1]
https://github.com/ncats/structure-indexer/blob/ce29589ae2aac5bbd35f26ff907e0a29244170ab/src/main/java/tripod/chem/indexer/StructureIndexer.java#L401

if it is kept it needs a try/catch

**Comment by dkatzel-ncats** [comment]
I didn't realize this was a ticket but it was removed on 9/21
